In [5]:
# Normal python list
x = [1,2,3,4]
print(x * 2)

# NumPy array
import numpy as np
y = np.array([1, 2, 3, 4])
print(y * 2)


[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [7]:
import numpy as np
# create an array
scores = np.array([85, 90, 78, 92])
# Do math on the array
print(scores.mean()) # average score
print(scores.max()) # highest score
print(scores + 5) #add 5 to every score


86.25
92
[90 95 83 97]


In [8]:
x = [3,8,12,10]
import numpy as np
y = np.array(x)
print ("mean value:",y.mean())
print ("max value:",y.max())
print ("min value:",y.min())
print ("power 2 value:",y**2)
print ("minus",y-3)
print ("add",y+3)
print ("multiplied values:",y*3)

mean value: 8.25
max value: 12
min value: 3
power 2 value: [  9  64 144 100]
minus [0 5 9 7]
add [ 6 11 15 13]
multiplied values: [ 9 24 36 30]


In [9]:
import numpy as np
y = np.array(x)
print(y-3)

[0 5 9 7]


In [ ]:
import pandas as pd
data = pd.read_csv ("C:/Users/abass/OneDrive/Desktop/Create a Folder/Python Analysis.csv")
print(data.head())   # First 5 rows
print(data.describe())  # Summary statistics
print(data["Math"].mean()) # Average math score


      Name  Math  English  Science
0    Alice    85       85       92
1      Bob    90       88       76
2  Charlie    78       78       80
3    Diana    92       95       89
4   Ethan     70       65       72
            Math    English    Science
count   5.000000   5.000000   5.000000
mean   83.000000  82.200000  81.800000
std     9.055385  11.388591   8.497058
min    70.000000  65.000000  72.000000
25%    78.000000  78.000000  76.000000
50%    85.000000  85.000000  80.000000
75%    90.000000  88.000000  89.000000
max    92.000000  95.000000  92.000000
83.0
