In [1]:
import numpy as np

In [51]:
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [5]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [7]:
# Accee the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3rd element on 1st row: ',arr[0, 2])

3rd element on 1st row:  3


In [54]:
# Accee the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3rd element on 2nd row: ',arr[1, 3])

3rd element on 2nd row:  9


In [55]:
# Access the element on the 2nd row, 5th column

In [ ]:
# Access the 3rd element of the second array of the 1st array:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
# this has 2 dimensionsal 
# so you go with '0', which is 1 - 6


6


In [57]:
#Use negative indexing from the 2nd element

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [58]:
# slice elements from the beginning to index 4 (not included):

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [59]:
# STEPs

# Return every other element from index 1 to index 5

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [9]:
# print from 2 to 12 with 3 steps 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[2:12])
print(arr[2:12:3])

[ 3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12]


In [62]:
arr = np.array(range(1, 8))
print(arr)

[1 2 3 4 5 6 7]


# Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print

In [66]:
# Return every other element from the entire array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])
print(arr[:])
print(arr)

[1 3 5 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [68]:
# From the second element, slice element from the index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[1, 1:4:2])

[7 8 9]
[7 9]


In [ ]:
# from both elements, slice index to index 4 (not included), this will require a 2-D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2])
print(arr[0:2, 1:4])
# 0:2 means that it will pick 1-5 and 6-10. (this is slicing)
# 1:4 is checking for both square brackets
# some form of rows and columns. 0-2 is focusing on the rows while 1-4 is focusing on the columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]
 [7 8 9]]


In [74]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [77]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# change data type from integer to boolean
# once it is not 0 (which represents false, it is trueeeee)
arr = np.array([1, 0, 3, -2])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


In [82]:
# print the shape of an array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [89]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(4, 3)
print(newarr)
newarr_2 = arr.reshape(2, 3, 2)
print(newarr_2)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
# Iterate on eachscalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [8]:
for x in (1:10):
    print(x)

SyntaxError: invalid syntax (3314473920.py, line 1)