In [ ]:
# Python match statement
day = 2

match day:
    case 1:
        print("Monday")
    case 2: 
        print("Tuesday")
    case 3: 
        print("Wednesday")
    case 4:
        print("Thursday")
    case 5:
        print("Friday")
    case 6:
        print("Saturday")
    case 7:
        print("Sunday")

Tuesday


In [3]:
# Default Value

day = 4

match day:
    case 6:
        print("Today is Saturday")
    case 7:
        print("Today is Sunday")
    case _:
        print("Looking forward to the weekend")

Looking forward to the weekend


In [5]:
# Shorthand

day = 7

match day:
    case 1 | 2 | 3 | 4 | 5:
        print("Today is a weekday")
    case 6 | 7:
        print("i love weekends")

i love weekends


In [9]:
month = 5
day = 5

match day:
    case 1 | 2 | 3 | 4 | 5 if month == 4:
        print("A weekday in April")
    case 1 | 2 | 3 | 4 | 5 if month == 5:
        print("A weekday in May")
    case _:
        print("No match")

A weekday in May


In [1]:
# NUMPY

import numpy


In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0 dimentional (42)
#1 dimensional ([1,2,3])
#2 dimensional ([1, 2, 3], [4, 5, 6])


In [9]:
a = np.array(42) # 0 dimensional
b = np.array([1, 2, 3]) # 1 dimensional
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dimensional
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print(b)
print(c)
print(d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3


In [11]:
difficult_assignment = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(difficult_assignment.ndim)

3


In [13]:
ghm = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
print(ghm.ndim)

3


In [16]:
icbd = np.array([[[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]], [[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]])
print(icbd.ndim)

4


In [18]:
sf = np.array([[[[1]]]])
print(sf)
print(sf.ndim)

[[[[1]]]]
4


In [ ]:
nbm = np.array([[[[[[[[[[10]]]]]]]]]])
print(nbm)
print(nbm.ndim)

[[[[[[[[[[10]]]]]]]]]]
10


: 